### ISSUE TITLE
关于RequestQueue的Stop()方法

### ISSUE THREAD

**Issue by Ordosbxy** [lishide/NoHttpConnecter#1]
您好，NoHttp官方Sample中的BaseActivity中在onDestroy()方法中
执行了mQueue.cancelBySign(object) 和 mQueue.stop()两个方法 

NoHttpConnecter在BaseActivity中在onDestroy()中只执行了mQueue.cancelBySign(object) 方法，

是否是因为封装了队列的单例模式封装后，一个App中只维护一个队列了，无需Stop，再App退出后自动Stop注销了？ 而NoHttp官方Sample中是每启动一个Activity，都会新建一个RequestQueue对象mQueue，所以它需要Stop？

**Comment by lishide** [comment]
没错，NoHttpConnecter在CallServer中进行了队列的单例模式封装，在onDestroy()中调用requestQueue.cancelBySign(sign)会按照标记取消请求。而NoHttp官方Sample是在BaseActivity初始化请求队列的，回调函数持有了activity，所以退出activity时需要停止队列。
